FROM public.ecr.aws/lambda/python:3.12

COPY pyproject.toml ${LAMBDA_TASK_ROOT}/
COPY app ${LAMBDA_TASK_ROOT}/app

RUN pip install --no-cache-dir ${LAMBDA_TASK_ROOT}

CMD ["app.lambda_handler.handler"]
